name = "MyMap"
uuid = "436e21ce-9421-41ab-9797-a9f786b469b4"
authors = ["Henry Gebhardt <hsggebhardt@fastmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
